sudo: required
services:
  - docker

before_install:
  - docker build -t andrewyct/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true andrewyct/docker-react-sample npm run test

language: generic